---
# Find and delete the OpenStack instances
- name: Fetch Instance Info
  os_server_facts:
    cloud: ospcloud
  register: server_info

- name: Delete instances
  os_server:
    cloud: ospcloud
    name: "{{ item.name }}"
    state: absent
  loop: "{{ server_info.ansible_facts.openstack_servers }}"
