---
# Provision the OpenStack servers. Servers for 3-tier app are defined in roles/osp-servers/defaults/main.yml.
# Runs on Ansible Tower on the workstation host.

- hosts: workstation
  become: yes

  roles:
    - osp-servers
