- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation

- hosts: workstation
  become: yes
  vars:
    server_list:
      - { name: 'app1', metadata: 'group=apps,deployment_name=QA', security_groups: 'apps' }
      - { name: 'app2', metadata: 'group=apps,deployment_name=QA', security_groups: 'apps' }
      - { name: 'db', metadata: 'group=appdbs,deployment_name=QA', security_groups: 'db' }
      - { name: 'frontend', metadata: 'group=frontends,deployment_name=QA', security_groups: 'frontend' }

  roles:
    - osp-servers
