---
# Start existing OpenStack instances without having to reprovision them

- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts

  tasks:
  - name: Start instances
    os_server_action:
      action: start
      server: "{{ item.name }}"
      wait: true
      timeout: 180
    loop: "{{ server_info.ansible_facts.openstack_servers }}"
