---
- name: Install postgres
  yum:
    name: postgresql-server
    state: latest

- name: Initialise the postgres database
  command: postgresql-setup initdb
  args:
    creates: "/var/lib/pgsql/data/PG_VERSION"

- name: Start and enable the postgres service
  service:
    name: postgresql.service
    state: started
    enabled: yes
